name: logging_colorful
description: Logging package with colors, no external dependencies. 
version: 1.2.0
repository: https://github.com/ethicnology/dart-logging-colorful

environment:
  sdk: ^3.3.0

dependencies:
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
