name: logging_colorful
description: Logging package with colors, no external dependencies. 
version: 1.3.2
repository: https://github.com/ethicnology/dart-logging-colorful

environment:
  sdk: ^3.3.0

dependencies:
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.0
